### ISSUE TITLE
MQTT user/pass

### ISSUE THREAD

**Issue by docx73** [BrianHepler/MMM-WeasleyClock#8]
Does not seem to have ability to connect to MQTT server with user/pass combination. When I try to connect I get authentication error as I have my mosquitto server setup to require user/pass. If authentication removed this module will connect.

**Comment by BrianHepler** [comment]
The module uses a specific user in order to differentiate itself from any other user. The patter is 'mirror-[UniqueID]'. So if you are using the unique ID of "goosnargh", then the mirror will attempt to log into the MQTT server as "mirror-goosnargh". 

The problem is that the mirror does not use nor expect to use a password. So the module supplies a password of "Get_Out_Of_My_Code". 

So the username of `mirror-goosnargh:Get_Out_Of_My_Code` will be passed in by the mirror. If you add that to your password file, it should work for you.

In hindsight, I realize that this is not a viable setup. I'll add the parameters to the configuration so that you can specify the mirror's username and password. I hope to push an update soon.

**Comment by BrianHepler** [comment]
Okay, I think I have the changes necessary to let you specify your own username & password. Please switch over to the TLS-Fix branch and try it out. I'm in the midst of testing it now, but I could always use some feedback.

**Comment by docx73** [comment]
Thank you kindly! Working great so far. Appreciate the module, just getting started with IoT and MQTT!
